name: diff-classifier
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=22.3.1
  - cudatoolkit=11.8
  - numpy
  - cmake
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.3.0
    - torchaudio==2.3.0
    - torchvision==0.18.0
    - diffusers
    - scikit-image
    - wandb
    - matplotlib
    - einops
    - transformers
    - accelerate
    - opencv-python
    - pandas